version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - 27054:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db

  websocket:
    build:
      dockerfile: ./Dockerfile
      target: websocket-builder
    ports:
      - 8000:8000
    depends_on:
      - server

  server:
    build:
      dockerfile: ./Dockerfile
      target: server-builder
    environment:
      - APP_DOMAIN=http://localhost:5000
      - PORT=5000
      - MG_HOST=mongodb
      - MG_USER=user
      - MG_PASS=root
      - MG_PORT=27017
      - DB_NAME=TODO
      - SECRET_KEY=6409671267:AAF1nl115GMCfQpEOXAx3MMihcXsZh8HOno
    ports:
      - 5000:5000
    depends_on:
      - mongodb

volumes:
  mongodb_data:
